// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aNaQlmR_D7lTGZIN6FOFxrtoJDKJfVk',
    appId: '1:867413260134:web:fbeaa08d51962f5b61faa7',
    messagingSenderId: '867413260134',
    projectId: 'smart-fan-ba8a6',
    authDomain: 'smart-fan-ba8a6.firebaseapp.com',
    storageBucket: 'smart-fan-ba8a6.firebasestorage.app',
    measurementId: 'G-R812NK0ND8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy5pY4Ah1jIiOBqsEGxwHsQIFBegxmYdQ',
    appId: '1:867413260134:android:2f17fd70d81aed2761faa7',
    messagingSenderId: '867413260134',
    projectId: 'smart-fan-ba8a6',
    storageBucket: 'smart-fan-ba8a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDXN2sA35P-JP5WPHo7JFoR9wzggajxDs',
    appId: '1:867413260134:ios:2f787e4275e01e0661faa7',
    messagingSenderId: '867413260134',
    projectId: 'smart-fan-ba8a6',
    storageBucket: 'smart-fan-ba8a6.firebasestorage.app',
    iosBundleId: 'com.example.monitoringTempe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDXN2sA35P-JP5WPHo7JFoR9wzggajxDs',
    appId: '1:867413260134:ios:2f787e4275e01e0661faa7',
    messagingSenderId: '867413260134',
    projectId: 'smart-fan-ba8a6',
    storageBucket: 'smart-fan-ba8a6.firebasestorage.app',
    iosBundleId: 'com.example.monitoringTempe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3aNaQlmR_D7lTGZIN6FOFxrtoJDKJfVk',
    appId: '1:867413260134:web:bc14f29ca082a4cc61faa7',
    messagingSenderId: '867413260134',
    projectId: 'smart-fan-ba8a6',
    authDomain: 'smart-fan-ba8a6.firebaseapp.com',
    storageBucket: 'smart-fan-ba8a6.firebasestorage.app',
    measurementId: 'G-VKFS9GJPRK',
  );
}
